      MODULE WIGNER_3j_I
      INTERFACE
      REAL(KIND(0.0D0)) FUNCTION WIGNER_3j(JA,JB,JC,MA,MB,MC)
      INTEGER, INTENT(IN) :: JA, JB, JC, MA, MB, MC
      END FUNCTION
      END INTERFACE
      END MODULE
